- name: Install prerequirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - software-properties-common

- name: Install PIP
  easy_install:
    name: pip
    state: present

- name: Install Python packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - boto

- debug: var=aws_access_key_id

- name: Copy boto config template
  template: src=boto.j2 dest="/home/vagrant/.boto" owner=vagrant group=vagrant