- name: Provision Vagrant box for running deployment script
  hosts: ansibleskeleton
  become: True
  remote_user: vagrant
  gather_facts: True
  roles:
    - geerlingguy.ansible
    - aws.credentials
    - vagrant.config